### ISSUE TITLE
Cache turned on and multiple widgets shows same content

### ISSUE THREAD

**Issue by webard** [WebberZone/top-10#26] opened 2016-03-23 09:53 UTC
Hi,
I have Top-10 on webpage with four widgets:
- today
- last 7 days
- last 30 days
- overall

When cache is turned off everything is ok, widgets show correct content. Unfortunately plugin cause high server without cache, so it is required. When cache is turned on, widgets: today, last 7 days, last 30 days shows same content, only overall show diffrent posts.

WP Super Cache is installed on page too.

**Comment by ajaydsouza** [comment] 2016-03-23 11:41
This is a duplicate of https://github.com/WebberZone/top-10/issues/21
This has been fixed in the current repo version and will be released in the next update

**Closed** 2016-03-26 09:41 UTC
Labels: duplicate
